export const weapons = {
    hammer: {
        name: "hammer",
        damage: [4, 6],
        stamina: 5,
        staminaDamage: 1,
        bleedDamage: 0,
        poison: 0,
        strength: true,
    },
    axe: {
        name: "axe",
        damage: [4, 6],
        stamina: 5,
        staminaDamage: 0,
        bleedDamage: 3,
        poison: 0,
        strength: true,
    },
    fist: {
        name: "fists",
        damage: [20, 23],
        stamina: 3,
        staminaDamage: 1,
        bleedDamage: 0,
        poison: 3,
        strength: true,
    },
    knife: {
        name: "knife",
        damage: [3, 4],
        stamina: 4,
        staminaDamage: 0,
        bleedDamage: 3,
        poison: 0,
        strength: true,
    },
    knife_poisoned: {
        name: "poisoned knife",
        damage: [3, 4],
        stamina: 0,
        staminaDamage: 0,
        bleedDamage: 3,
        poison: 1,
        strength: true,
    },
    syringe_poisoned: {
        name: "poisoned syringe",
        damage: [0, 0],
        stamina: 5,
        staminaDamage: 0,
        bleedDamage: 3,
        poison: 3,
        strength: true,
    },
    chainsaw: {
        name: "chainsaw",
        damage: [9, 11],
        stamina: 5,
        staminaDamage: 0,
        bleedDamage: 0,
        poison: 0,
        strength: true,
    },
    pistol: {
        name: "pistol",
        damage: [16, 20],
        stamina: 6,
        staminaDamage: 0,
        bleedDamage: 0,
        poison: 0,
        strength: false,
    },
    rifle: {
        name: "assault rifle",
        damage: [24, 30],
        stamina: 10,
        staminaDamage: 0,
        bleedDamage: 0,
        poison: 0,
        strength: false,
    },
    shotgun: {
        name: "shotgun",
        damage: [20, 26],
        stamina: 8,
        staminaDamage: 0,
        bleedDamage: 0,
        poison: 0,
        strength: false,
    },
    molotov: {
        name: "molotov",
        damage: [20, 26],
        stamina: 8,
        staminaDamage: 0,
        bleedDamage: 0,
        poison: 0,
        strength: false,
    },
    flashbang: {
        name: "flashbang",
        damage: [0, 0],
        stamina: 99,
        staminaDamage: 0,
        bleedDamage: 0,
        poison: 0,
        strength: false,
    },
    nailgun: {
        name: "nailgun",
        damage: [5, 8],
        stamina: 8,
        staminaDamage: 1,
        bleedDamage: 3,
        poison: 0,
        strength: false,
    }

}